/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import popup_frame.FormTambahEntryObat;
import popup_frame.FormPembayaran;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ItemPenjualan;
import model.Pelanggan;
import model.Transaksi;
import services.PelangganServices;
import services.PenjualanItemServices;
import services.PenjualanServices;

/**
 *
 * @author TUF
 */
public class FormPenjualan extends javax.swing.JFrame {

    private DefaultTableModel model;
    private ItemPenjualan itemDipilih;

    /**
     * Creates new form DataPegawai
     */
    public FormPenjualan() {
        initComponents();
        this.setLocationRelativeTo(null);

        model = new DefaultTableModel();
        table_entry_item.setModel(model);
        model.addColumn("id_entry_transaksi");
        model.addColumn("kode_obat");
        model.addColumn("nama_barang");
        model.addColumn("quantity");
        model.addColumn("harga_item");
        model.addColumn("total");

        kode();
        loadData();

        initiateOpsiPelanggan();
        validateItemchanged();
    }

    private void validateItemchanged() {
        try {
            List<ItemPenjualan> result = PenjualanItemServices.ambilDataItemPenjualan(label_kodePenjualan.getText());
            Double totalPembelian = 0.0;

            btn_bayar.setEnabled(false);
            btn_resetData.setEnabled(false);

            if (!result.isEmpty()) {
                btn_bayar.setEnabled(true);
                btn_resetData.setEnabled(true);

                for (ItemPenjualan penjualan : result) {
                    totalPembelian += penjualan.getTotal();
                }
            }

            label_totalPembelian.setText(totalPembelian.toString());
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void loadData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        btn_hapusItem.setEnabled(false);
        btn_ubahItem.setEnabled(false);
        try {
            List<ItemPenjualan> result = PenjualanItemServices.ambilDataItemPenjualan(label_kodePenjualan.getText());

            for (ItemPenjualan itemPenjualan : result) {
                // your logic here
                System.out.println(itemPenjualan.toString());

                Object[] o = new Object[6];
                o[0] = itemPenjualan.getIdEntryTransaksi();
                o[1] = itemPenjualan.getKodeObat();
                o[2] = itemPenjualan.getNamaBarang();
                o[3] = itemPenjualan.getQuantity();
                o[4] = itemPenjualan.getHargaItem();
                o[5] = itemPenjualan.getTotal();

                model.addRow(o);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void kode() {
        try {
            String result = PenjualanServices.ambilKodeTransaksi();
            label_kodePenjualan.setText(result);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void initiateOpsiPelanggan() {
        try {
            List<Pelanggan> result = PelangganServices.ambilDataPelanggan();

            for (Pelanggan pelanggan : result) {
                // your logic here
                select_pelanggan.addItem(pelanggan.getNama_pelanggan() + ";" + pelanggan.getId_pelanggan());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void softReset() {
        btn_tambahBarang.setEnabled(true);
        btn_bayar.setEnabled(true);
        btn_resetData.setEnabled(true);

        btn_hapusItem.setEnabled(false);
        btn_ubahItem.setEnabled(false);

        table_entry_item.clearSelection();

        itemDipilih = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_totalPembelian = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_bayar = new javax.swing.JButton();
        btn_resetData = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_tambahBarang = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        label_namaItemDipilih = new javax.swing.JLabel();
        label_hargaItemDipilih = new javax.swing.JLabel();
        label_kodePenjualan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_entry_item = new javax.swing.JTable();
        btn_hapusItem = new javax.swing.JButton();
        btn_ubahItem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        select_pelanggan = new javax.swing.JComboBox<>();
        refreshButton = new javax.swing.JButton();
        Navbar = new javax.swing.JMenuBar();
        menuMaster = new javax.swing.JMenu();
        menuObat = new javax.swing.JMenuItem();
        menuPegawai = new javax.swing.JMenuItem();
        menuPelanggan = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        menuPenjualan = new javax.swing.JMenuItem();
        menuLaporan = new javax.swing.JMenu();
        menuLaporanPenjualan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/my-logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setToolTipText("");
        jPanel4.setAlignmentX(0.0F);
        jPanel4.setAlignmentY(0.0F);
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 40));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("TOTAL");

        label_totalPembelian.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        label_totalPembelian.setForeground(new java.awt.Color(204, 255, 204));
        label_totalPembelian.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_totalPembelian.setText("233000");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(label_totalPembelian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_totalPembelian)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_bayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallet.png"))); // NOI18N
        btn_bayar.setText("BAYAR");
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });

        btn_resetData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/restart.png"))); // NOI18N
        btn_resetData.setText("CLEAR");
        btn_resetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetDataActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("24 April 2021 11:01");

        btn_tambahBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pills-1.png"))); // NOI18N
        btn_tambahBarang.setText("Tambahkan Barang");
        btn_tambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahBarangActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 102, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setToolTipText("");
        jPanel5.setAlignmentX(0.0F);
        jPanel5.setAlignmentY(0.0F);
        jPanel5.setPreferredSize(new java.awt.Dimension(0, 40));

        label_namaItemDipilih.setBackground(new java.awt.Color(204, 255, 204));
        label_namaItemDipilih.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        label_namaItemDipilih.setForeground(new java.awt.Color(204, 255, 204));
        label_namaItemDipilih.setText("- Pilih Barang -");

        label_hargaItemDipilih.setBackground(new java.awt.Color(204, 255, 204));
        label_hargaItemDipilih.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        label_hargaItemDipilih.setForeground(new java.awt.Color(204, 255, 204));
        label_hargaItemDipilih.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_hargaItemDipilih.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_namaItemDipilih, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_hargaItemDipilih, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_namaItemDipilih)
                    .addComponent(label_hargaItemDipilih))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label_kodePenjualan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_kodePenjualan.setText("KODE_TRANSAKSI");

        table_entry_item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_entry_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_entry_itemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_entry_item);

        btn_hapusItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thrash.png"))); // NOI18N
        btn_hapusItem.setText("Hapus");
        btn_hapusItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusItemActionPerformed(evt);
            }
        });

        btn_ubahItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit.png"))); // NOI18N
        btn_ubahItem.setText("Ubah");
        btn_ubahItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahItemActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Kode Penjualan :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Pelanggan :");

        select_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_pelangganActionPerformed(evt);
            }
        });

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_kodePenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(select_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1167, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btn_hapusItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_ubahItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_tambahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(984, 984, 984))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(962, 962, 962)
                                .addComponent(btn_resetData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_bayar)))
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_kodePenjualan)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(select_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resetData, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tambahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreshButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_ubahItem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapusItem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        menuMaster.setText("Master");

        menuObat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuObat.setText("Obat");
        menuObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuObatActionPerformed(evt);
            }
        });
        menuMaster.add(menuObat);

        menuPegawai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuPegawai.setText("Pegawai");
        menuPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPegawaiActionPerformed(evt);
            }
        });
        menuMaster.add(menuPegawai);

        menuPelanggan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        menuPelanggan.setText("Pelanggan");
        menuPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPelangganActionPerformed(evt);
            }
        });
        menuMaster.add(menuPelanggan);

        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        menuMaster.add(menuLogout);

        Navbar.add(menuMaster);

        menuTransaksi.setText("Transaksi");

        menuPenjualan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuPenjualan.setText("Penjualan");
        menuPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenjualanActionPerformed(evt);
            }
        });
        menuTransaksi.add(menuPenjualan);

        Navbar.add(menuTransaksi);

        menuLaporan.setText("Laporan");

        menuLaporanPenjualan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        menuLaporanPenjualan.setText("Laporan Penjualan");
        menuLaporanPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanPenjualanActionPerformed(evt);
            }
        });
        menuLaporan.add(menuLaporanPenjualan);

        Navbar.add(menuLaporan);

        setJMenuBar(Navbar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuObatActionPerformed
        // TODO add your handling code here:
        InventoryObat f = new InventoryObat();
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuObatActionPerformed

    private void menuPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPegawaiActionPerformed
        // TODO add your handling code here:
        DataPegawai f = new DataPegawai();
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuPegawaiActionPerformed

    private void menuPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPelangganActionPerformed
        // TODO add your handling code here:
        DataPelanggan f = new DataPelanggan();
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuPelangganActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
        Login f = new Login();
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenjualanActionPerformed
        // TODO add your handling code here:
        FormPenjualan f = new FormPenjualan();
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuPenjualanActionPerformed

    private void menuLaporanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanPenjualanActionPerformed
        // TODO add your handling code here:
        FormLaporanPenjualan f = new FormLaporanPenjualan();
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuLaporanPenjualanActionPerformed

    private void btn_tambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahBarangActionPerformed
        // TODO add your handling code here:
        String currentKodeTransaksi = label_kodePenjualan.getText();

        FormTambahEntryObat f = new FormTambahEntryObat(currentKodeTransaksi, null);
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_tambahBarangActionPerformed

    private void table_entry_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_entry_itemMouseClicked
        // TODO add your handling code here:
        btn_tambahBarang.setEnabled(false);
        btn_bayar.setEnabled(false);
        btn_resetData.setEnabled(false);

        btn_hapusItem.setEnabled(true);
        btn_ubahItem.setEnabled(true);

        int i = table_entry_item.getSelectedRow();
        if (i == -1) {
            return;
        }

        Integer detail_idItem = (Integer) model.getValueAt(i, 0);
        String detail_kodeObat = (String) model.getValueAt(i, 1);
        String detail_namaObat = (String) model.getValueAt(i, 2);
        Integer detail_quantity = (Integer) model.getValueAt(i, 3);
        Double detail_hargaItem = (Double) model.getValueAt(i, 4);
        Double detail_total = (Double) model.getValueAt(i, 5);

        ItemPenjualan detailItem = new ItemPenjualan();
        detailItem.setIdEntryTransaksi(detail_idItem);
        detailItem.setKodeTransaksi(label_kodePenjualan.getText());
        detailItem.setKodeObat(detail_kodeObat);
        detailItem.setNamaBarang(detail_namaObat);
        detailItem.setQuantity(detail_quantity);
        detailItem.setHargaItem(detail_hargaItem);
        detailItem.setTotal(detail_total);

        itemDipilih = detailItem;

        label_namaItemDipilih.setText(itemDipilih.getNamaBarang());
        label_hargaItemDipilih.setText(itemDipilih.getHargaItem().toString());

        System.out.println(detailItem.toString());
    }//GEN-LAST:event_table_entry_itemMouseClicked

    private void btn_hapusItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusItemActionPerformed
        // TODO add your handling code here:
        try {
            PenjualanItemServices.deleteData(itemDipilih.getIdEntryTransaksi());
            loadData();
            validateItemchanged();

            softReset();

            JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Apotik Pharmacy - Asep Supriyadi", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_hapusItemActionPerformed

    private void btn_resetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetDataActionPerformed
        // TODO add your handling code here:
        try {
            String kodeTransaksi = label_kodePenjualan.getText();
            PenjualanItemServices.resetEntryData(kodeTransaksi);
            loadData();
            validateItemchanged();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_resetDataActionPerformed

    private void btn_ubahItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahItemActionPerformed
        // TODO add your handling code here:
        String currentKodeTransaksi = label_kodePenjualan.getText();

        FormTambahEntryObat f = new FormTambahEntryObat(currentKodeTransaksi, itemDipilih);
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ubahItemActionPerformed

    private void select_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_pelangganActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_select_pelangganActionPerformed

    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayarActionPerformed
        // TODO add your handling code here:
        Transaksi transaksi = new Transaksi();
        String[] pelanggan = select_pelanggan.getSelectedItem().toString().split(";");
        Integer idPelanggan = Integer.parseInt(pelanggan[1]);

        transaksi.setIdPelanggan(idPelanggan);
        transaksi.setKodeTransaksi(label_kodePenjualan.getText());
        transaksi.setTotalPembelian(Double.parseDouble(label_totalPembelian.getText()));

        FormPembayaran f = new FormPembayaran(transaksi);
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_bayarActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        softReset();
    }//GEN-LAST:event_refreshButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Navbar;
    private javax.swing.JButton btn_bayar;
    private javax.swing.JButton btn_hapusItem;
    private javax.swing.JButton btn_resetData;
    private javax.swing.JButton btn_tambahBarang;
    private javax.swing.JButton btn_ubahItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_hargaItemDipilih;
    private javax.swing.JLabel label_kodePenjualan;
    private javax.swing.JLabel label_namaItemDipilih;
    private javax.swing.JLabel label_totalPembelian;
    private javax.swing.JMenu menuLaporan;
    private javax.swing.JMenuItem menuLaporanPenjualan;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenuItem menuObat;
    private javax.swing.JMenuItem menuPegawai;
    private javax.swing.JMenuItem menuPelanggan;
    private javax.swing.JMenuItem menuPenjualan;
    private javax.swing.JMenu menuTransaksi;
    private javax.swing.JButton refreshButton;
    private javax.swing.JComboBox<String> select_pelanggan;
    private javax.swing.JTable table_entry_item;
    // End of variables declaration//GEN-END:variables
}
