/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package popup_frame;

import frame.FormPenjualan;
import java.awt.Desktop;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import model.ItemPenjualan;
import model.Transaksi;
import services.PenjualanItemServices;
import services.PenjualanServices;

/**
 *
 * @author TUF
 */
public class FormPembayaran extends javax.swing.JFrame {

    private Transaksi transaksiSaatIni;

    /**
     * Creates new form FormPembayaran
     *
     * @param reqTransaksi
     */
    public FormPembayaran(Transaksi reqTransaksi) {
        initComponents();
        this.setLocationRelativeTo(null);
        transaksiSaatIni = reqTransaksi;

        label_totalPembelian.setText(reqTransaksi.getTotalPembelian().toString());
        btn_cetak.setEnabled(false);
        btn_lunas.setEnabled(false);
    }

    private void checkTunai() {
        Double totalPembelian = Double.parseDouble(label_totalPembelian.getText());
        Double currentTunai = (Double) txt_tunai.getValue();

        Double kembalian = currentTunai - totalPembelian;

        txt_kembali.setText(kembalian.toString());

        if (currentTunai >= totalPembelian) {
            btn_lunas.setEnabled(true);
        } else if (currentTunai < totalPembelian) {
            btn_lunas.setEnabled(false);
        }
    }

    private void hardReset() {
        txt_tunai.setValue(0D);
        txt_kembali.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        entry_judul_form = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        dfsa = new javax.swing.JLabel();
        btn_lunas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        label_totalPembelian = new javax.swing.JLabel();
        label_untuk_total = new javax.swing.JLabel();
        txt_kembali = new javax.swing.JTextField();
        dfsa1 = new javax.swing.JLabel();
        txt_tunai = new javax.swing.JSpinner();
        btn_cetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 903));

        jPanel3.setBackground(new java.awt.Color(0, 102, 51));

        entry_judul_form.setBackground(new java.awt.Color(204, 255, 204));
        entry_judul_form.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        entry_judul_form.setForeground(new java.awt.Color(204, 255, 204));
        entry_judul_form.setText("Form Pembayaran");

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back.png"))); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entry_judul_form)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_back)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(entry_judul_form)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_back)
                .addContainerGap())
        );

        dfsa.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        dfsa.setForeground(new java.awt.Color(0, 153, 51));
        dfsa.setText("Tunai :");

        btn_lunas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallet.png"))); // NOI18N
        btn_lunas.setText("Lunas");
        btn_lunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lunasActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));

        label_totalPembelian.setBackground(new java.awt.Color(204, 255, 204));
        label_totalPembelian.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label_totalPembelian.setForeground(new java.awt.Color(204, 255, 204));
        label_totalPembelian.setText("1000");

        label_untuk_total.setBackground(new java.awt.Color(204, 255, 204));
        label_untuk_total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_untuk_total.setForeground(new java.awt.Color(204, 255, 204));
        label_untuk_total.setText("Total");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_totalPembelian)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(label_untuk_total)
                    .addContainerGap(409, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(label_totalPembelian)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(label_untuk_total)
                    .addContainerGap(55, Short.MAX_VALUE)))
        );

        txt_kembali.setBackground(new java.awt.Color(253, 253, 236));
        txt_kembali.setEnabled(false);
        txt_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kembaliActionPerformed(evt);
            }
        });
        txt_kembali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_kembaliKeyReleased(evt);
            }
        });

        dfsa1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        dfsa1.setForeground(new java.awt.Color(0, 153, 51));
        dfsa1.setText("Kembali :");

        txt_tunai.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txt_tunai.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 100.0d));
        txt_tunai.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txt_tunaiStateChanged(evt);
            }
        });
        txt_tunai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tunaiKeyReleased(evt);
            }
        });

        btn_cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Print-2.png"))); // NOI18N
        btn_cetak.setText("Cetak Nota");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 140, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(dfsa)
                                .addGap(18, 18, 18)
                                .addComponent(txt_tunai, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(dfsa1)
                                .addGap(18, 18, 18)
                                .addComponent(txt_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btn_lunas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dfsa)
                    .addComponent(txt_tunai, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dfsa1))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_lunas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        hardReset();

        FormPenjualan f = new FormPenjualan();
        f.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btn_backActionPerformed

    private void txt_tunaiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txt_tunaiStateChanged
        // TODO add your handling code here:
        Double currentValue = (Double) txt_tunai.getValue();

        if (currentValue <= 0) {
            txt_tunai.setValue(0D);
        }

        checkTunai();
    }//GEN-LAST:event_txt_tunaiStateChanged

    private void txt_kembaliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kembaliKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kembaliKeyReleased

    private void txt_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kembaliActionPerformed

    private void btn_lunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lunasActionPerformed
        // TODO add your handling code here:
        transaksiSaatIni.setTotalDibayarkan((Double) txt_tunai.getValue());
        transaksiSaatIni.setTotalKembalian(Double.parseDouble(txt_kembali.getText()));

        try {
            PenjualanServices.tambahDataTransaksi(transaksiSaatIni);

            hardReset();

            JOptionPane.showMessageDialog(null, "Transaksi selesai", "Apotik Pharmacy - Asep Supriyadi", JOptionPane.INFORMATION_MESSAGE);

            btn_back.setEnabled(false);
            btn_lunas.setEnabled(false);
            btn_cetak.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_lunasActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URL("http://localhost/GenerateReportPhamarcy?fk=" + transaksiSaatIni.getKodeTransaksi()).toURI());

            FormPenjualan f = new FormPenjualan();
            f.setVisible(true);
            this.setVisible(false);

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void txt_tunaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tunaiKeyReleased
        // TODO add your handling code here
    }//GEN-LAST:event_txt_tunaiKeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormPembayaran().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_lunas;
    private javax.swing.JLabel dfsa;
    private javax.swing.JLabel dfsa1;
    private javax.swing.JLabel entry_judul_form;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label_totalPembelian;
    private javax.swing.JLabel label_untuk_total;
    private javax.swing.JTextField txt_kembali;
    private javax.swing.JSpinner txt_tunai;
    // End of variables declaration//GEN-END:variables
}
